name: DevCycle variable diff action
description: A GitHub Action for generating a summary of changes to DevCycle variables.
author: DevCycle
inputs:
  client-id:
    description: "Your DevCycle client ID"
    required: true
  client-secret:
    description: "Your DevCycle client secret"
    required: true
  github-token:
    description: "The GitHub token for your repo"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'