name: DevCycle Feature Flag Insights for Pull Requests
description: Identifies changes in DevCycle Feature Flags within a PR, adds a comment to your PRs.
author: DevCycleHQ
branding:
  color: blue
  icon: flag
inputs:
  github-token:
    description: "The GitHub token for your repo"
    required: true
runs:
  using: node12
  main: dist/index.js