on: [pull_request, push]

jobs:
  dvc-variable-diff:
    runs-on: ubuntu-latest
    name: Fetch DevCycle variable diff
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: DevCycleHQ/feature-flag-pr-insights-action@DVC-6760-add-dvc-referrer-headers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
