on: [pull_request]

jobs:
  dvc-variable-diff:
    runs-on: ubuntu-latest
    name: Fetch DevCycle variable diff
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
