on: [pull_request]

jobs:
  dvc-variable-diff:
    runs-on: ubuntu-latest
    name: Fetch DevCycle variable diff
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
